#!/bin/sh

cd /root/massa/massa-client
wallet_info=$(./massa-client -p YOUR_PASSWORD_HERE wallet_info)
get_addresses=$(./massa-client -p YOUR_PASSWORD_HERE get_addresses YOUR_ADDRESS_HERE)
get_status=$(./massa-client -p YOUR_PASSWORD_HERE get_status)

wallet_info_result=$(echo "$wallet_info" | grep -oP "Balance: final=\K[0-9.]+(?=, candidate)")
echo "wallet_balance $wallet_info_result"

wallet_active_rolls=$(echo "$wallet_info" | grep -oP "Rolls: active=\K[0-9.]+(?=, final)")
echo "wallet_active_rolls $wallet_active_rolls"

last_cycle_blocks=$(echo "$get_addresses" | grep -oP "Cycle \d+ \(candidate\): produced \d+ and missed \d+ blocks with \d+ active rolls")
#echo "$last_cycle_blocks"
produced_blocks=$(echo "$last_cycle_blocks" | grep -oP "produced \K\d+")
echo "produced_blocks_last_cycle $produced_blocks"

missed_blocks=$(echo "$last_cycle_blocks" | grep -oP "missed \K\d+")
echo "missed_blocks_last_cycle $missed_blocks"

current_cycle=$(echo "$last_cycle_blocks" | grep -oP "Cycle \K\d+")
echo "current_cycle $current_cycle"

block_reward=$(echo "$get_status" | grep -oP "Block reward: \K[0-9.]+(?=)")
echo "block_reward $block_reward"

in_connections=$(echo "$get_status" | grep -oP "In connections: \K\d+")
echo "in_connections $in_connections"

out_connections=$(echo "$get_status" | grep -oP "Out connections: \K\d+")
echo "out_connections $out_connections"
